<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'irishgauge\\blackcube' => '/cubes/BlackCube.php',
                'irishgauge\\cube' => '/cubes/Cube.php',
                'irishgauge\\dividendcubedraw' => '/cubes/DividendCubeDraw.php',
                'irishgauge\\exception' => '/exceptions/Exception.php',
                'irishgauge\\nospecialinterestexception' => '/exceptions/NoSpecialInterestException.php',
                'irishgauge\\pinkcube' => '/cubes/PinkCube.php',
                'irishgauge\\specialinterestcubealreadyplacedexception' => '/exceptions/SpecialInterestCubeAlreadyPlacedException.php',
                'irishgauge\\station' => '/Station.php',
                'irishgauge\\toofewcubesexception' => '/exceptions/TooFewCubesException.php',
                'irishgauge\\toomanycubesexception' => '/exceptions/TooManyCubesException.php',
                'irishgauge\\whitecube' => '/cubes/WhiteCube.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
